### ISSUE TITLE
[Bug Report] [Regression (#624)]  - Crate not Documentable with Rust 1.69.0, rustix v0.38.12

### ISSUE THREAD

**Issue by KyteProject** [bytecodealliance/rustix#818]
Same issue as #624 has appeared in  v0.38.12 while running `cargo doc`

```
❯ cargo version -v
cargo 1.69.0 (6e9a83356 2023-04-12)
release: 1.69.0
commit-hash: 6e9a83356b70586d4b77613a6b33f9ea067b9cdf
commit-date: 2023-04-12
host: x86_64-unknown-linux-gnu
libgit2: 1.5.0 (sys:0.16.0 vendored)
libcurl: 7.86.0-DEV (sys:0.4.59+curl-7.86.0 vendored ssl:OpenSSL/1.1.1q)
os: Ubuntu 22.04 (jammy) [64-bit]
```

```
❯ cargo doc
    Updating crates.io index
  Downloaded windows-targets v0.48.5
  Downloaded thiserror-impl v1.0.48
  Downloaded windows-core v0.51.1
  Downloaded errno v0.3.3
  Downloaded thiserror v1.0.48
  Downloaded either v1.9.0
  Downloaded log v0.4.20
  Downloaded env_logger v0.10.0
  Downloaded bitflags v2.4.0
  Downloaded anyhow v1.0.75
  Downloaded memchr v2.6.3
  Downloaded sysinfo v0.29.9
  Downloaded aho-corasick v1.0.5
  Downloaded regex v1.9.5
  Downloaded syn v2.0.31
  Downloaded rustix v0.38.12
  Downloaded regex-syntax v0.7.5
  Downloaded regex-automata v0.3.8
  Downloaded windows_x86_64_gnu v0.48.5
  Downloaded linux-raw-sys v0.4.5
  Downloaded windows v0.51.1
  Downloaded 21 crates (16.8 MB) in 0.80s (largest was `windows` at 12.3 MB)
   Compiling autocfg v1.1.0
   Compiling crossbeam-utils v0.8.16
    Checking cfg-if v1.0.0
   Compiling libc v0.2.147
    Checking scopeguard v1.2.0
   Compiling windows_x86_64_gnu v0.48.5
    Checking memchr v2.6.3
    Checking unicode-ident v1.0.11
   Compiling rayon-core v1.11.0
 Documenting cfg-if v1.0.0
   Compiling rustix v0.38.12
    Checking bitflags v2.4.0
    Checking linux-raw-sys v0.4.5
    Checking regex-syntax v0.7.5
 Documenting scopeguard v1.2.0
 Documenting unicode-ident v1.0.11
    Checking either v1.9.0
 Documenting memchr v2.6.3
   Compiling anyhow v1.0.75
 Documenting regex-syntax v0.7.5
 Documenting linux-raw-sys v0.4.5
 Documenting bitflags v2.4.0
   Compiling proc-macro2 v1.0.66
   Compiling thiserror v1.0.48
 Documenting either v1.9.0
    Checking termcolor v1.2.0
    Checking once_cell v1.18.0
    Checking log v0.4.20
    Checking humantime v2.1.0
    Checking aho-corasick v1.0.5
 Documenting log v0.4.20
 Documenting termcolor v1.2.0
 Documenting humantime v2.1.0
 Documenting once_cell v1.18.0
 Documenting lazy_static v1.4.0
    Checking quote v1.0.33
    Checking lazy_static v1.4.0
   Compiling memoffset v0.9.0
   Compiling crossbeam-epoch v0.9.15
    Checking syn v2.0.31
    Checking regex-automata v0.3.8
 Documenting proc-macro2 v1.0.66
    Checking regex v1.9.5
   Compiling thiserror-impl v1.0.48
 Documenting windows_x86_64_gnu v0.48.5
    Checking windows-targets v0.48.5
    Checking windows-core v0.51.1
 Documenting crossbeam-utils v0.8.16
    Checking windows v0.51.1
    Checking crossbeam-channel v0.5.8
 Documenting anyhow v1.0.75
 Documenting libc v0.2.147
 Documenting aho-corasick v1.0.5
    Checking num_cpus v1.16.0
    Checking is-terminal v0.4.9
    Checking env_logger v0.10.0
 Documenting memoffset v0.9.0
    Checking crossbeam-deque v0.8.3
    Checking rayon v1.7.0
 Documenting quote v1.0.33
 Documenting windows-targets v0.48.5
 Documenting crossbeam-channel v0.5.8
    Checking sysinfo v0.29.9
 Documenting crossbeam-epoch v0.9.15
 Documenting windows-core v0.51.1
 Documenting regex-automata v0.3.8
 Documenting syn v2.0.31
 Documenting crossbeam-deque v0.8.3
 Documenting windows v0.51.1
 Documenting thiserror-impl v1.0.48
 Documenting regex v1.9.5
 Documenting rustix v0.38.12
thread 'rustc' panicked at 'no resolution for "std::io::Error" MacroNS DefId(0:880 ~ rustix[5cf1]::io)', src/librustdoc/passes/collect_intra_doc_links.rs:391:32
stack backtrace:
   0:     0x7f1c0a6bb31a - std::backtrace_rs::backtrace::libunwind::trace::ha9053a9a07ca49cb
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5      
   1:     0x7f1c0a6bb31a - std::backtrace_rs::backtrace::trace_unsynchronized::h9c2852a457ad564e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f1c0a6bb31a - std::sys_common::backtrace::_print_fmt::h457936fbfaa0070f
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f1c0a6bb31a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5779d7bf7f70cb0c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f1c0a71eb6e - core::fmt::write::h5a4baaff1bcd3eb5
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1232:17
   5:     0x7f1c0a6ae2c5 - std::io::Write::write_fmt::h4bc1f301cb9e9cce
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/io/mod.rs:1684:15
   6:     0x7f1c0a6bb0e5 - std::sys_common::backtrace::_print::h5fcdc36060f177e8
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f1c0a6bb0e5 - std::sys_common::backtrace::print::h54ca9458b876c8bf
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f1c0a6bde5f - std::panicking::default_hook::{{closure}}::hbe471161c7664ed6
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:271:22
   9:     0x7f1c0a6bdb9b - std::panicking::default_hook::ha3500da57aa4ac4f
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:290:9
  10:     0x7f1c0d91f8b5 - <rustc_driver_impl[fb92b3e21ac03dce]::DEFAULT_HOOK::{closure#0}::{closure#0} as core[911a585bea10363d]::ops::function::FnOnce<(&core[911a585bea10363d]::panic::panic_info::PanicInfo,)>>::call_once::{shim:vtable#0}
  11:     0x7f1c0a6be69d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h6507bddc3eebb4a5
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:2001:9
  12:     0x7f1c0a6be69d - std::panicking::rust_panic_with_hook::h50c09d000dc561d2
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:696:13
  13:     0x7f1c0a6be419 - std::panicking::begin_panic_handler::{{closure}}::h9e2b2176e00e0d9c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:583:13
  14:     0x7f1c0a6bb786 - std::sys_common::backtrace::__rust_end_short_backtrace::h5739b8e512c09d02
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:150:18
  15:     0x7f1c0a6be122 - rust_begin_unwind
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
  16:     0x7f1c0a71aec3 - core::panicking::panic_fmt::hf33a1475b4dc5c3e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
  17:     0x55833a683624 - <rustdoc[483c6e22976f34cb]::passes::collect_intra_doc_links::LinkCollector>::resolve_path
  18:     0x55833a68374e - <rustdoc[483c6e22976f34cb]::passes::collect_intra_doc_links::LinkCollector>::resolve
  19:     0x55833a687364 - <rustdoc[483c6e22976f34cb]::passes::collect_intra_doc_links::LinkCollector as rustdoc[483c6e22976f34cb]::visit::DocVisitor>::visit_item
  20:     0x55833a69067a - <rustdoc[483c6e22976f34cb]::passes::collect_intra_doc_links::LinkCollector as rustdoc[483c6e22976f34cb]::visit::DocVisitor>::visit_inner_recur
  21:     0x55833a68aa7c - <rustdoc[483c6e22976f34cb]::passes::collect_intra_doc_links::LinkCollector as rustdoc[483c6e22976f34cb]::visit::DocVisitor>::visit_item
  22:     0x55833a69067a - <rustdoc[483c6e22976f34cb]::passes::collect_intra_doc_links::LinkCollector as rustdoc[483c6e22976f34cb]::visit::DocVisitor>::visit_inner_recur
  23:     0x55833a68aa7c - <rustdoc[483c6e22976f34cb]::passes::collect_intra_doc_links::LinkCollector as rustdoc[483c6e22976f34cb]::visit::DocVisitor>::visit_item
  24:     0x55833a6820a2 - rustdoc[483c6e22976f34cb]::passes::collect_intra_doc_links::collect_intra_doc_links
  25:     0x55833a5ca32e - <rustc_session[b87ece769e9b9511]::session::Session>::time::<rustdoc[483c6e22976f34cb]::clean::types::Crate, rustdoc[483c6e22976f34cb]::core::run_global_ctxt::{closure#7}>
  26:     0x55833a6f5dd0 - rustdoc[483c6e22976f34cb]::core::run_global_ctxt
  27:     0x55833a5ca5b9 - <rustc_session[b87ece769e9b9511]::session::Session>::time::<(rustdoc[483c6e22976f34cb]::clean::types::Crate, rustdoc[483c6e22976f34cb]::config::RenderOptions, rustdoc[483c6e22976f34cb]::formats::cache::Cache), rustdoc[483c6e22976f34cb]::main_args::{closure#1}::{closure#0}::{closure#0}::{closure#0}>
  28:     0x55833a4c8d57 - <rustc_middle[1a4ce3311a146f18]::ty::context::GlobalCtxt>::enter::<rustdoc[483c6e22976f34cb]::main_args::{closure#1}::{closure#0}::{closure#0}, core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>>
  29:     0x55833a533fce - rustc_span[fab0eb11f1fed58d]::with_source_map::<core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>, rustc_interface[bd8390756bd7a52a]::interface::run_compiler<core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>, rustdoc[483c6e22976f34cb]::main_args::{closure#1}>::{closure#0}::{closure#0}>
  30:     0x55833a4a6474 - <scoped_tls[473f62cd2eff9842]::ScopedKey<rustc_span[fab0eb11f1fed58d]::SessionGlobals>>::set::<rustc_interface[bd8390756bd7a52a]::interface::run_compiler<core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>, rustdoc[483c6e22976f34cb]::main_args::{closure#1}>::{closure#0}, core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>>
  31:     0x55833a5e19a0 - std[685882fd5f6d52e5]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[bd8390756bd7a52a]::util::run_in_thread_pool_with_globals<rustc_interface[bd8390756bd7a52a]::interface::run_compiler<core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>, rustdoc[483c6e22976f34cb]::main_args::{closure#1}>::{closure#0}, core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>>    
  32:     0x55833a6ac1dd - <<std[685882fd5f6d52e5]::thread::Builder>::spawn_unchecked_<rustc_interface[bd8390756bd7a52a]::util::run_in_thread_pool_with_globals<rustc_interface[bd8390756bd7a52a]::interface::run_compiler<core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>, rustdoc[483c6e22976f34cb]::main_args::{closure#1}>::{closure#0}, core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>>::{closure#0}::{closure#0}, core[911a585bea10363d]::result::Result<(), rustc_span[fab0eb11f1fed58d]::ErrorGuaranteed>>::{closure#1} as core[911a585bea10363d]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  33:     0x7f1c0a6c8593 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h39990b24eedef2ab
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:1987:9
  34:     0x7f1c0a6c8593 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h01a027258444143b
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:1987:9
  35:     0x7f1c0a6c8593 - std::sys::unix::thread::Thread::new::thread_start::ha4f1cdd9c25884ba
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys/unix/thread.rs:108:17
  36:     0x7f1c0a3f0b43 - <unknown>
  37:     0x7f1c0a482a00 - <unknown>
  38:                0x0 - <unknown>

error: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.69.0 (84c898d65 2023-04-16) running on x86_64-unknown-linux-gnu

note: compiler flags: --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not document `rustix`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2021 --crate-type lib --crate-name rustix /home/dan/.cargo/registry/src/github.com-1ecc6299db9ec823/rustix-0.38.12/src/lib.rs --cap-lints allow -o /mnt/d/Projects/rust/d2rust/target/doc --cfg 'feature="alloc"' --cfg 'feature="default"' --cfg 'feature="std"' --cfg 'feature="termios"' --cfg 'feature="use-libc-auxv"' --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=151 -C metadata=98897f2b64c80654 -L dependency=/mnt/d/Projects/rust/d2rust/target/debug/deps --extern bitflags=/mnt/d/Projects/rust/d2rust/target/debug/deps/libbitflags-feddec123a9c8f02.rmeta --extern linux_raw_sys=/mnt/d/Projects/rust/d2rust/target/debug/deps/liblinux_raw_sys-6645ead011e47a91.rmeta --crate-version 0.38.12 --cfg static_assertions --cfg linux_raw --cfg linux_like --cfg linux_kernel` (exit status: 101)
warning: build failed, waiting for other jobs to finish...
```

**Comment by sunfishcode** [comment]
Thanks for the report! This is now fixed in rustix 0.38.13.
